# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0004_auto_20190331_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='songkey',
            new_name='key',
        ),
    ]
