# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0005_auto_20190331_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='like_it',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='like_it',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
