# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0009_auto_20190331_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='user_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='album',
            name='user_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='track',
            name='user_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='track',
            name='user_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
