# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0010_auto_20190406_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='loudness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='mode',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='time_signature',
            field=models.FloatField(null=True),
        ),
    ]
