# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0012_auto_20190407_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.CharField(max_length=32),
        ),
    ]
